### ISSUE TITLE
DashJS throws Error: Merkle root from the diff doesn't match calculated merkle root ....

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#244] opened 2022-02-10 02:41 UTC
DashJS throws `Error: Merkle root from the diff doesn't match calculated merkle root after diff is applied at SimplifiedMNList.applyDiff`

## Current Behavior
<img width="1038" alt="Screenshot 2022-02-10 at 03 34 26" src="https://user-images.githubusercontent.com/15247893/153326987-afd8b167-98c8-4025-9f6e-7df7b6fe8364.png">

## Steps to Reproduce (for bugs)
```js
const Dash = require("dash");

const client = new Dash.Client({
    network: "testnet",
    wallet: {
        mnemonic: "arena light cheap control apple buffalo indicate rare motor valid accident isolate",
    },
});

// Accessing an account allow you to transact with the Dash Network
client.getWalletAccount().then(async (account) => {
    console.log("Funding address", account.getUnusedAddress().address);

    const balance = account.getConfirmedBalance();
    console.log("Confirmed Balance", balance);

    if (balance > 0) {
        // Creating an identity is the basis of all interactions with the Dash Platform
        const identity = await client.platform.identities.register()

        // Prepare a new document containing a simple hello world sent to a hypothetical tutorial contract
        const document = await platform.documents.create(
            'tutorialContract.note',
            identity,
            { message: 'Hello World' },
        );

        // Broadcast the document into a new state transition
        await platform.documents.broadcast({ create: [document] }, identity);
    }
});
```

## Your Environment
* dash@3.21.7

**Comment by mayoreee** [comment] 2022-02-11 10:28
Related to #112

**Comment by SamKirby22** [comment] 2022-02-11 10:43
The root cause is being tracked under issue 112 - new symptoms have been added to there hence closing this issue.

**Comment by SamKirby22** [comment] 2022-02-11 10:45
@maverick - looks like my Admin rights were lost when moving to monorepo - can you regrant my power please :-)

**Comment by mayoreee** [comment] 2022-02-11 10:45
I think I can close the issue. Should I?

**Closed** 2022-02-11 10:48 UTC
Labels: bug

**Comment by SamKirby22** [comment] 2022-02-11 10:55
Thanks :-)
